### ISSUE TITLE
Implement Faraway Replicas

### ISSUE THREAD

**Issue by serdardalgic** [EnterpriseDB/terraform-provider-biganimal#122]
BigAnimal recently announced [Faraway Replicas](https://www.enterprisedb.com/blog/release-radar-faraway-replicas-edb-biganimal-clusters). 

It would be a nice addition to include the Faraway Replicas to the TF Provider.

**Comment by GabriFedi97** [comment]
I'd like to work on this one.

**Comment by edbamolvyavahare** [comment]
closed by mistake due to a PR was merged

**Comment by serdardalgic** [comment]
While closing this ticket, Here is a short summary of all the Faraway Replicas development that are added to our Terraform Provider. Thanks to @edbamolvyavahare for your hard work 👏 
1. Within #153, faraway_cluster_ids field is added to the `biganimal_cluster` resource/data-source
2. #149 introduces `biganimal_faraway_replica` data-source that takes a faraway replica ID as `cluster_id` and gives the information about that faraway replica cluster.
3. And finally #145 introduces `biganimal_faraway_replica` resource that creates faraway replicas when a `source_cluster_id` is provided.
