### ISSUE TITLE
Add CSP connection to BigAnimal Projects 

### ISSUE THREAD

**Issue by serdardalgic** [EnterpriseDB/terraform-provider-biganimal#129]
Projects resource and data sources are being developed within #119. We have `cloud_providers` field in the implementation (See #125 for more details), but there is no automatic CSP connection to the newly created projects. We need to implement an automated way for creating the CSP connections.

It would be a good idea to have a separate resource, e.g.,`biganimal_csp_connect` that would do the equivalent of work from the`setup-csp` and `update-csp` commands of the BigAnimal CLI. 

For more information, please visit [Connecting your cloud](https://www.enterprisedb.com/docs/biganimal/latest/getting_started/02_connecting_to_your_cloud/) documentation.

**Comment by YanniHu1996** [comment]
close it as https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/144 has been merged
