### ISSUE TITLE
the check for completion should also check the cluster's `phase`

### ISSUE THREAD

**Issue by nstott** [EnterpriseDB/terraform-provider-biganimal#20]
We currently do not check the cluster's `phase` when discovering if a change was successful.
we should wait until the cluster is in a healthy phase, as well as has a `biganimal.com/deployed` condition before we mark a change as being successful

**Comment by serdardalgic** [comment]
We can make use of https://portal.biganimal.com/api/docs/#/Clusters/getClusterPhases here, I think.
