### ISSUE TITLE
Resource Not Found returned if there are clusters with the same name

### ISSUE THREAD

**Issue by kunliuedb** [EnterpriseDB/terraform-provider-biganimal#25]
### Terraform Version
Terraform v1.3.2

### Affected Resource(s)

- cluster_data

### Actual Behavior
`Error: Resource Not Found
with data.biganimal_cluster.this,
on data.tf line 10, in data "biganimal_cluster" "this":
10: data "biganimal_cluster" "this" {
`

### Root cause
The root cause is the logic [here](https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/072f3aa96819265ddd3ce57d02f350c7c3364a61/pkg/api/clusterClient.go#L97)
`if len(clusters.Data) != 1 {
		return &models.Cluster{}, Error404
}`

**Comment by serdardalgic** [comment]
I would like to close this PR with the next release, when we release the solution implemented in #118.
