### ISSUE TITLE
Fix using multiple providers at the same time.

### ISSUE THREAD

**Issue by serdardalgic** [EnterpriseDB/terraform-provider-biganimal#40]
We need to fix the way we're using multiple providers during development. The way we're solving using terraform providers during development is not ideal and we hit bugs like #29.  

We need to update our documentation to reflect this accordingly.

########

We're using `terraformrc` to configure terraform cli to benefit from [Development Overrides](https://developer.hashicorp.com/terraform/cli/config/config-file#development-overrides-for-provider-developers). When we also use other providers, such as `hashicorp/random`, these providers also need to be initialized. Therefore, we end up with a chicken and egg problem:
* terraform plan not being able to run because it cannot find the hashicorp/random provider
* Terraform init command cannot find the BigAnimal provider, thus the creation of `terraform.lock.hcl` file fails. Not only `terraform init` command, but also `terraform providers lock` command doesn't solve this issue.

In that case, we end up with situations like #29. 

A workaround for now, is to comment out the BigAnimal provider related code, e.g.

```diff
 terraform {
   required_providers {
-    biganimal = {
-      source  = "biganimal"
-      version = "0.3.1"
-    }
     random = {
       source  = "hashicorp/random"
...
-resource "biganimal_cluster" "this_resource" {
-  cluster_name = var.cluster_name
-
-  allowed_ip_ranges {
-    cidr_block  = "127.0.0.1/32"
-    description = "localhost"
...
-  pg_type            = "epas"
-  pg_version         = "14"
-  private_networking = false
-  cloud_provider     = "azure"
-  region             = "eastus2"
-  replicas           = 1
-}
-
-output "password" {
-  sensitive = true
-  value = resource.biganimal_cluster.this_resource.password
-}
```
And then running the `terraform init` command only for random provider.

**Comment by YanniHu1996** [comment]
The provider is published  https://registry.terraform.io/providers/EnterpriseDB/biganimal/. These issues are not relevant anymore
