### ISSUE TITLE
Failed to create cluster with pgvector enabled

### ISSUE THREAD

**Issue by kunliuedb** [EnterpriseDB/terraform-provider-biganimal#438]
**Describe the bug**
Failed to create cluster with pgvector enabled

**To Reproduce**
Provision a cluster with the resource example https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/main/examples/resources/biganimal_cluster/single_node/resource.tf

```
╷
│ Error: Unsupported argument
│
│   on resource.tf line 82, in resource "biganimal_cluster" "single_node_cluster":
│   82:   pgvector              = true
│
│ An argument named "pgvector" is not expected here.
╵
```

**Comment by wai-wong-edb** [comment]
fixed in v0.7.0
