### ISSUE TITLE
GH workflow for docs generation

### ISSUE THREAD

**Issue by serdardalgic** [EnterpriseDB/terraform-provider-biganimal#55]
Now we're generating the docs of the terraform repository by running go generate command manually. 

https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/main/main.go#L18 here is the go:generate definition that runs the [tfplugindocs](https://github.com/hashicorp/terraform-plugin-docs#tfplugindocs) on the existing command, and it generated the examples and docs directories. 

Ideally, we can have a GH workflow that would generate the docs automatically. Until we reach this point, a workflow that would show the diff, if the docs are not correctly generated would also be fine. 

Either instead of tfplugindocs or in combination with tfplugindocs, https://terraform-docs.io/how-to/github-action/ this GH action may also be used. Please investigate further. 

If you have an alternative solution suggestion, feel free to mention in this issue.

**Comment by YanniHu1996** [comment]
close it as https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/144 has been merged

**Comment by serdardalgic** [comment]
We've added `go generate` to our pre-commit hooks, so that tfplugindocs generate command would run and tell the PR owner if there are problems related to documentation generation. 

I'm closing this one.
