### ISSUE TITLE
settings in pg_bouncer cannot be aligned during a cluster update

### ISSUE THREAD

**Issue by sszhao1020** [EnterpriseDB/terraform-provider-biganimal#565]
**Describe the bug**
During creating a cluster with pgBouncer disabled or (no pgbouncer block ), the `terraform.tfstate` will become
```
                        "pg_bouncer": {
                            "is_enabled": false,
                            "settings": null
                        },
```
During the cluster update with the PgBouncer block specified  (PGB is still disabled). it always returns `1 to change` (even with settings = null)
```
  # biganimal_cluster.single_node_cluster will be updated in-place
  ~ resource "biganimal_cluster" "single_node_cluster" {
        id                            = "prj_0gww9tNHWIS9GBLN/p-clrdlv54cm"
      ~ pg_bouncer                    = {
          + settings   = (known after apply)
            # (1 unchanged attribute hidden)
        }
        # (27 unchanged attributes hidden)

        # (5 unchanged blocks hidden)
    }
```

**To Reproduce**
1. create a cluster with pg_bouncer disabled
2. update the cluster with pg_bouncer block specified

**Expected behavior**
If the `pg_bouncer.is_enabled` is always false, validating settings is unnecessary.

**Terraform and Provider Version:**
v0.11.0

**Affected Resource(s):**
Please list the resources as a list, for example:
- biganimal_cluster resource

**Comment by wai-wong-edb** [comment]
PR here https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/566
