### ISSUE TITLE
Adding readonly connections attribute to cluster resource

### ISSUE THREAD

**Issue by pizzacapricciosa** [EnterpriseDB/terraform-provider-biganimal#57]

**Comment by pizzacapricciosa** [comment]
In BigAnimal an HA pgcluster can be created with a read only workload option.
If that option is activated the read queries can be directed to the secondary nodes improving performances.

This option is described in the following on line doc, in the connection section
 https://www.enterprisedb.com/docs/biganimal/latest/getting_started/creating_a_cluster/#additional-settings-tab
 
 The API for the cluster creation are offering that option as described below
 
 {
  "clusterName": "My Cluster",
  "clusterType": "cluster",
  "password": "perfectenschlag",
  "privateNetworking": false,
  "replicas": 1,
  "allowedIpRanges": [
    {
      "cidrBlock": "252.1.1.1/24",
      "description": "New York"
    },
    {
      "cidrBlock": "167.3.2.1/32",
      "description": "Boston"
    }
  ],
  "pgConfig": [
    {
      "name": "application_name",
      "value": "restore-test"
    },
    {
      "name": "array_nulls",
      "value": "off"
    }
  ],
  "pgType": {
    "pgTypeId": "epas"
  },
  "pgVersion": {
    "pgVersionId": "13"
  },
  "provider": {
    "cloudProviderId": "azure"
  },
  "readOnlyConnections": false,
  "cspAuth": false,
  "region": {
    "regionId": "australiaeast"
  },
  "instanceType": {
    "instanceTypeId": "azure:Standard_D16s_v3"
  },
  "storage": {
    "volumeTypeId": "azurepremiumstorage",
    "volumePropertiesId": "P1",
    "iops": "120",
    "size": "4 Gi"
  },
  "clusterArchitecture": {
    "clusterArchitectureId": "single",
    "nodes": 1
  },
  "backupRetentionPeriod": "6d"
}


Here is the GUI when you want to enable that option in an existing cluster

<img width="1792" alt="Screenshot 2022-11-15 at 17 15 20" src="https://user-images.githubusercontent.com/92850939/201970663-3257b8d8-9b84-4609-aa3b-ffd7a102ed23.png">

**Comment by kunliuedb** [comment]
@pizzacapricciosa The fix has been merged, you can pull the latest code and build provider. I also added an [example](https://github.com/EnterpriseDB/terraform-provider-biganimal/blob/main/examples/ha_cluster_resource/resource.tf) for ha cluster, feel free to take a try and verify. I close this issue.
