### ISSUE TITLE
Data Sources Cluster doesn't show Azure Private Service name

### ISSUE THREAD

**Issue by sszhao1020** [EnterpriseDB/terraform-provider-biganimal#585]
**Describe the bug**
For an Azure BAH private cluster, there is Service Name in the connection page which will be used for private connection 
<img width="908" alt="image" src="https://github.com/user-attachments/assets/10a254ae-a9a4-490b-ae25-badefbea384e">
However, this info is not included in the terraform data resource cluster output.

**To Reproduce**
1. Create a Private BAH Azure cluster
2. run data-sources/biganimal_cluster to list the cluster-info
```

Outputs:

backup_retention_period = "6d"
cloud_provider = "bah:aws"
cluster_architecture = {
  "id" = "ha"
  "name" = "Primary/Standby High Availability"
  "nodes" = 3
}
cluster_name = "shan-bah-azure"
created_at = "2024-09-18 11:56:56.697961 +0800 CST"
csp_auth = false
faraway_replica_ids = toset([])
instance_type = "aws:c5.large"
logs_url = "pg-logs-tenant-4d5efe97-de01-4cba-8f6d-6386bedff17c"
metrics_url = "http://p-gwng7wrqek-metrics.private.pg.biganimal.io:8080"
pe_allowed_principal_ids = toset([
  "703425358540",
])
pg_type = "epas"
pg_version = "15"
pgvector = false
phase = "Cluster in healthy state"
post_gis = false
private_networking = true
read_only_connections = true
region = "us-east-1"
resizing_pvc = tolist([])
ro_connection_uri = "postgresql://edb_admin@p-gwng7wrqek-ro.private.pg.biganimal.io:5432/edb_admin"
service_account_ids = toset([])
storage = {
  "iops" = "3000"
  "size" = "4 Gi"
  "throughput" = "125"
  "volume_properties" = "gp3"
  "volume_type" = "gp3"
}
superuser_access = false
volume_snapshot_backup = false
```
**Expected behavior**
The Service Name(Azure PLS) info should be displayed in the output
 
**Screenshots**

**Terraform and Provider Version:**
1.0.0

**Affected Resource(s):**
Please list the resources as a list, for example:
- biganimal_cluster data source

**Comment by wai-wong-edb** [comment]
fixed in v1.1
