### ISSUE TITLE
Dependabot should create commits that are valid conventional commits

### ISSUE THREAD

**Issue by nstott** [EnterpriseDB/terraform-provider-biganimal#63]
We currently have a workflow that ensures that commit messages follow the conventional commit guidelines.
Currently dependabot doesn't create 'valid' commit messages.  Please see https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/45/commits

According to the dependabot documentation, this can be resolved by adding a stanza to the dependabot config as follows
```yaml
    commit-message:
      prefix: "chore(dependancies): "
```

**Comment by serdardalgic** [comment]
Dependabot uses conventional commits when it detects a workflow. This PR #45 was created before we enabled the conventional commits. Dependabot conventional commits work fine, see https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/59. 

Closing this Issue.
