### ISSUE TITLE
Add `pre-commit-terraform` pre-commit check

### ISSUE THREAD

**Issue by mbiagetti** [EnterpriseDB/terraform-provider-biganimal#69]
I would suggest to adopt also the pre-commit git hooks to take care of Terraform configurations

See https://github.com/antonbabenko/pre-commit-terraform

**Comment by serdardalgic** [comment]
`terraform_fmt` and `tfupdate` hooks are integrated into our pre-commit check in #182 . 

Closing this GH Issue.
