### ISSUE TITLE
go vet error for the tools package

### ISSUE THREAD

**Issue by serdardalgic** [EnterpriseDB/terraform-provider-biganimal#78]
go vet pre-commit check is failing for the tools package. 
```
go vet...................................................................Failed
- hook id: go-vet
- exit code: 1

package github.com/EnterpriseDB/terraform-provider-biganimal/tools: build constraints exclude all Go files in /Users/serdar.dalgic/DEVELOPMENT/TERRAFORM_PROVIDER/terraform-provider-biganimal/tools
```

We don't know for now why it happens. The package is a standalone package that only allows the installation of tfplugindocs, so it doesn't interfere with the provider code. That's why It would be safe to exclude it from the go vet check, which is done in #77.

But we need to investigate why it happens.

**Comment by YanniHu1996** [comment]
I try to run `go vet ./tools/tools.go`, and got the following error
```
ools/tools.go:8:2: import "github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs" is a program, not an importable package
```
I guess `go vet` considers  `tfplugindocs` is an incorrect import ,
the https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/77 is a good way to fix this issue

**Comment by YanniHu1996** [comment]
close it as https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/77 has been merged,
