### ISSUE TITLE
tfplugindocs generate empty lines at the end of docs

### ISSUE THREAD

**Issue by serdardalgic** [EnterpriseDB/terraform-provider-biganimal#86]
Either because of the templates or something wicked with our configuration, tfplugindocs command a.k.a. `make docs` a.k.a. `go generate` generates empty lines at the end of `docs/resources/cluster.md` and `docs/resources/region.md`. 

We need to figure out why it happens and fix it. It's quite annoying while generating the docs. 

Because of this faulty generation, the pre-commit github action check fails, that's why the `github_actions` label.

**Comment by YanniHu1996** [comment]
I raised a related PR to fix this issue, https://github.com/hashicorp/terraform-plugin-docs/pull/237

**Comment by serdardalgic** [comment]
@YanniHu1996 's PR is merged into terraform-plugin-docs, and as described [here](https://github.com/hashicorp/terraform-plugin-docs/pull/237#issuecomment-1490387044), we're using the terraform-plugin-docs version that includes this fix. 

We also enabled the `go generate` which runs `tfplugindocs generate` command in each and every PR. 

I'm closing this GH Issue. Thanks for your work, @YanniHu1996 . 🎉
